channels:
- conda-forge
dependencies:
- python=3.10.9
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==1.24.2
  - pandas==1.5.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
